plugins {
    id 'com.android.application'
}

android {
    namespace 'com.comscore.helloworldexample'
    compileSdk 37

    defaultConfig {
        applicationId "com.comscore.helloworldexample"
        minSdk 21
        targetSdk 37
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    implementation 'com.comscore:android-analytics:6.+'
    implementation 'androidx.preference:preference:1.1.1'
}
